[Eth]
NetworkId = 1007
SyncMode = "full"
DiscoveryURLs = []
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
DatabaseCache = 512
DatabaseFreezer = ""
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 0
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""
RPCGasCap = 0
RPCTxFeeCap = 0e+00

[Eth.Miner]
GasFloor = 100000000
GasCeil = 8000000
GasPrice = 500000000000000
Recommit = 3000000000
Noverify = false

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 300000000000
PriceLimit = 500000000000000
PriceBump = 10
AccountSlots = 4096
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60

[Shh]
MaxMessageSize = 1048576
MinimumAcceptedPOW = 2e-01
RestrictConnectionBetweenLightClients = true

[Node]
DataDir = "/data/newchain/testnet/nodedata"
NoUSB = true
IPCPath = "geth.ipc"
HTTPHost = "127.0.0.1"
HTTPPort = 8808
HTTPCors = ["*"]
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "txpool", "net"]
WSHost = ""
WSPort = 8546
WSModules = ["net", "web3", "eth"]
GraphQLHost = ""
GraphQLPort = 8547
GraphQLVirtualHosts = ["localhost"]

[Node.P2P]
MaxPeers = 25
NoDiscovery = false
BootstrapNodes = ["enode://0a4cf1b2f21f1caae594aea2c9a2ffced3db9bd71f595f9273a6ef2fbc11d68dd0f12867bddb0ca20a9157e11b20bbd4b755a4b28a3515583ac9327c528a5ffe@18.178.210.219:38311"]
BootstrapNodesV5 = ["enode://0a4cf1b2f21f1caae594aea2c9a2ffced3db9bd71f595f9273a6ef2fbc11d68dd0f12867bddb0ca20a9157e11b20bbd4b755a4b28a3515583ac9327c528a5ffe@18.178.210.219:38311"]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":38311"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000
