[Eth]
NetworkId = 1007
SyncMode = "full"
DiscoveryURLs = []
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
DatabaseCache = 512
DatabaseFreezer = ""
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 0
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""
RPCGasCap = 25000000
RPCTxFeeCap = 1e+00

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 300000000000
PriceLimit = 100
PriceBump = 10
AccountSlots = 4096
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60

[Shh]
MaxMessageSize = 1048576
MinimumAcceptedPOW = 2e-01
RestrictConnectionBetweenLightClients = true

[Node]
DataDir = "/data/newchain/testnet/nodedata"
NoUSB = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8801
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "txpool", "net"]
WSHost = ""
WSPort = 8546
WSModules = ["net", "web3", "eth"]
GraphQLHost = ""
GraphQLPort = 8547
GraphQLVirtualHosts = ["localhost"]

[Node.P2P]
MaxPeers = 25
NoDiscovery = false
BootstrapNodes = ["enode://056ad86e11958090b317229c737447874e3ff6f0371b0e85cdef3395498a240995146f68b2ddeec60ddacb794227bde36688ca3bf6d00c2356b311321c38ed9a@52.192.95.29:38311"]
BootstrapNodesV5 = ["enode://056ad86e11958090b317229c737447874e3ff6f0371b0e85cdef3395498a240995146f68b2ddeec60ddacb794227bde36688ca3bf6d00c2356b311321c38ed9a@52.192.95.29:38311"]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":38311"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000
