[Eth]
NetworkId = 26888
SyncMode = "full"
EthDiscoveryURLs = []
SnapDiscoveryURLs = []
NoPruning = true
NoPrefetch = false
TxLookupLimit = 0
TransactionHistory = 0
StateHistory = 90000
LightPeers = 100
DatabaseCache = 512
DatabaseFreezer = ""
TrieCleanCache = 154
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 102
Preimages = false
FilterLogCacheSize = 32
EnablePreimageRecording = false
RPCGasCap = 50000000
RPCEVMTimeout = 5000000000
RPCTxFeeCap = 10000.0

[Eth.Miner]
#Etherbase = "0x009f1ddaf7f528e60a7c560c51ae997cd4709cc3"
GasFloor = 0
GasCeil = 21000000
GasPrice = 50000000000000
Recommit = 2000000000
NewPayloadTimeout = 2000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 50000000000000
PriceBump = 10
AccountSlots = 65536
GlobalSlots = 1048576
AccountQueue = 65536
GlobalQueue = 1048576
Lifetime = 10800000000000

[Eth.BlobPool]
Datadir = "blobpool"
Datacap = 10737418240
PriceBump = 100

[Eth.GPO]
Blocks = 20
Percentile = 60
MaxHeaderHistory = 1024
MaxBlockHistory = 1024
MaxPrice = 5000000000000000
IgnorePrice = 50000000000000

[Node]
DataDir = "/data/abcore/testnet/nodedata"
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["debug", "txpool", "net", "web3", "eth"]
AuthAddr = "127.0.0.1"
AuthPort = 8551
AuthVirtualHosts = ["*"]
WSHost = "0.0.0.0"
WSPort = 8546
WSModules = ["debug", "txpool", "net", "web3", "eth"]
GraphQLVirtualHosts = ["*"]
BatchRequestLimit = 1000
BatchResponseMaxSize = 25000000

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
DiscoveryV4 = true
BootstrapNodes = ["enode://6a1fab59fe0fb617f244f7b3a811d9f6ae3f9f0c45cde4afd27c1a76e96b47fa8755e701ede323bd9c370a763194d2adfe684c433a50c8d20d60c64c70e26cd3@52.68.5.208:33333"]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":33333"
DiscAddr = ""
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Metrics]
HTTP = "127.0.0.1"
Port = 6360
InfluxDBEndpoint = "http://localhost:8386"
InfluxDBDatabase = "geth"
InfluxDBUsername = "test"
InfluxDBPassword = "test"
InfluxDBTags = "host=localhost"
InfluxDBToken = "test"
InfluxDBBucket = "geth"
InfluxDBOrganization = "geth"